<?php
/**
 * SystemStrap Block Filters & Action Hooks
 *
 * @package systemstrap
 */

// Exit if accessed directly.
defined( 'ABSPATH' ) || exit;

if ( ! function_exists( 'strap_get_class_name' ) ) {
	/**
	 * Retrieve the `className` attribute from a block.
	 *
	 * @param array $block The block array.
	 * @return string The class name or an empty string if not set.
	 */
	function strap_get_class_name( array $block ): string {
		return $block['attrs']['className'] ?? '';
	}
}

if ( ! function_exists( 'strap_do_block_action' ) ) {
	/**
	 * Execute a WordPress action hook inside block content.
	 *
	 * @param string $hook The name of the action hook to execute.
	 * @return string The content generated by the action hook.
	 */
	function strap_do_block_action( string $hook = '' ): string {
		ob_start();
		do_action( $hook );
		$block_action = ob_get_clean();
		return $block_action ? $block_action : '';
	}
}

if ( ! function_exists( 'strap_action_hook' ) ) {
	/**
	 * Add hooks using the core/separator block.
	 *
	 * This function modifies the content of the core/separator block by
	 * adding hooks dynamically. The separator block should have the trigger
	 * class `strap-action-hook` followed by the desired hook name.
	 *
	 * @param string $block_content The original block content.
	 * @param array  $block         The block attributes.
	 * @return string The modified block content with the action hook applied.
	 */
	function strap_action_hook( string $block_content, array $block ): string {
		$class_name = strap_get_class_name( $block );
		
		if ( ! $class_name ) {
			return $block_content;
		}

		// Exit if the class does not contain the trigger class 'strap-action-hook'.
		if ( ! str_contains( $class_name, 'strap-action-hook' ) ) {
			return $block_content;
		}

		// Extract the action hook name from the class name (after 'strap-action-hook ').
		$action = explode( 'strap-action-hook ', $class_name )[1] ?? '';

		// If an action is found, execute it and replace the block content.
		if ( $action && 'strap-action-hook ' . $action === strap_get_class_name( $block ) ) {
			$block_content = strap_do_block_action( $action );
		}

		return $block_content;
	}

	add_filter( 'render_block_core/separator', 'strap_action_hook', 10, 2 );
}

if ( ! function_exists( 'strap_replace_block_content' ) ) {
	/**
	 * Replace content in the block's rendered HTML.
	 *
	 * @param string $block_content The block's rendered content.
	 * @param string $search        The search string.
	 * @param string $replace       The replacement string.
	 * @param int    $limit         The limit of replacements. Default is 1.
	 * @return string The updated block content.
	 */
	function strap_replace_block_content( string $block_content, string $search, string $replace, int $limit = 1 ): string {
		$pattern = '/' . preg_quote( $search, '/' ) . '/';
		$result  = preg_replace( $pattern, $replace, $block_content, $limit );
		return is_string( $result ) ? $result : $block_content;
	}
}

/**
 * Filter: Adds structured data to core/template-part blocks.
 */
add_filter( 'render_block_core/template-part', 'strap_structured_data_parts_block_filter', 10, 2 );
function strap_structured_data_parts_block_filter( string $block_content, array $block ): string {
	$class_name = strap_get_class_name( $block );
	if ( ! $class_name ) {
		return $block_content;
	}

	$itemtype = match ( true ) {
		str_contains( $class_name, 'main-search' ) => 'SearchResultsPage',
		str_contains( $class_name, 'main-index' ) ||
			str_contains( $class_name, 'main-single' ) ||
			str_contains( $class_name, 'main-archive' ) => 'Blog',
		default => 'WebPage'
	};

	$itemtype_label = ' itemtype="https://schema.org/' . esc_html( $itemtype ) . '" itemscope ';

	if ( str_contains( $class_name, 'site-header' ) ) {
		return strap_replace_block_content(
			$block_content,
			'<header',
			'<header id="masthead" aria-label="Site header" itemtype="https://schema.org/WPHeader" itemscope role="banner"'
		);
	}

	if ( str_contains( $class_name, 'site-main' ) ) {
		$page_title = esc_attr( wp_get_document_title() );
		return strap_replace_block_content(
			$block_content,
			'<main',
			'<main' . $itemtype_label . 'role="main" aria-label="Main content: ' . $page_title . '"'
		);
	}

	if ( str_contains( $class_name, 'site-footer' ) ) {
		return strap_replace_block_content(
			$block_content,
			'<footer',
			'<footer id="colophon" aria-label="Site footer" itemtype="https://schema.org/Organization" itemscope role="contentinfo"'
		);
	}

	if ( str_contains( $class_name, 'secondary-content' ) || str_contains( $class_name, 'tertiary-content' ) ) {
		return strap_replace_block_content(
			$block_content,
			'<aside',
			'<aside role="complementary" aria-label="Sidebar"'
		);
	}

	return $block_content;
}

/**
 * Filter: Adds schema.org markup to single articles.
 */
add_filter( 'render_block_core/group', 'strap_single_content_block_filter', 10, 2 );
function strap_single_content_block_filter( string $block_content, array $block ): string {
	$class_name = strap_get_class_name( $block );

	if ( str_contains( $class_name, 'hentry' ) ) {
		return strap_replace_block_content(
			$block_content,
			'class',
			'itemtype="https://schema.org/CreativeWork" itemscope class'
		);
	}

	return $block_content;
}

/**
 * Filter: Adds itemprop to post excerpt blocks.
 */
add_filter( 'render_block_core/post-excerpt', 'strap_post_excerpt_content_block_filter', 10, 2 );
function strap_post_excerpt_content_block_filter( string $block_content, array $block ): string {
	$class_name = strap_get_class_name( $block );

	if ( str_contains( $class_name, 'entry-summary' ) ) {
		return strap_replace_block_content(
			$block_content,
			'class',
			'itemprop="text" class'
		);
	}

	return $block_content;
}

/**
 * Filter: Adds aria-label to entry meta blocks.
 */
add_filter( 'render_block_core/group', 'strap_entry_meta_content_block_filter', 10, 2 );
function strap_entry_meta_content_block_filter( string $block_content, array $block ): string {
	$class_name = strap_get_class_name( $block );

	if ( str_contains( $class_name, 'entry-meta' ) ) {
		return strap_replace_block_content(
			$block_content,
			'class',
			'aria-label="Entry meta" class'
		);
	}

	return $block_content;
}

/**
 * Filter: Adds aria-label to post navigation block.
 */
add_filter( 'render_block_core/group', 'strap_post_nav_content_block_filter', 10, 2 );
function strap_post_nav_content_block_filter( string $block_content, array $block ): string {
	$class_name = strap_get_class_name( $block );

	if ( str_contains( $class_name, 'post-navigation' ) ) {
		return strap_replace_block_content(
			$block_content,
			'class',
			'aria-label="Posts" class'
		);
	}

	return $block_content;
}

/**
 * Filter: Adds itemprop to post content blocks.
 */
add_filter( 'render_block_core/post-content', 'strap_post_content_content_block_filter', 10, 2 );
function strap_post_content_content_block_filter( string $block_content, array $block ): string {
	$class_name = strap_get_class_name( $block );

	if ( str_contains( $class_name, 'entry-content' ) ) {
		return strap_replace_block_content(
			$block_content,
			'class',
			'itemprop="text" class'
		);
	}

	return $block_content;
}

/**
 * Filter: Adds schema.org markup to navigation blocks.
 */
add_filter( 'render_block_core/navigation', 'strap_navigation_content_block_filter', 10, 2 );
function strap_navigation_content_block_filter( string $block_content, array $block ): string {
	return str_replace(
		[ '<nav', '<ul class="wp-block-navigation__container', '<li', '<a' ],
		[
			'<nav role="navigation"',
			'<ul role="list" itemtype="https://schema.org/SiteNavigationElement" itemscope class="wp-block-navigation__container',
			'<li itemprop="name" role="listitem"',
			'<a itemprop="url"'
		],
		$block_content
	);
}

/**
 * Filter: Adds schema.org markup to categories blocks.
 */
add_filter( 'render_block_core/categories', 'strap_categories_content_block_filter', 10, 2 );
function strap_categories_content_block_filter( string $block_content, array $block ): string {
	return str_replace(
		[ '<ul', '<li', '<a' ],
		[
			'<ul aria-label="Category navigation" itemtype="https://schema.org/SiteNavigationElement" itemscope',
			'<li itemprop="name"',
			'<a itemprop="url"'
		],
		$block_content
	);
}

/**
 * Filter: Adds schema.org markup to archives blocks.
 */
add_filter( 'render_block_core/archives', 'strap_archives_content_block_filter', 10, 2 );
function strap_archives_content_block_filter( string $block_content, array $block ): string {
	return str_replace(
		[ '<ul', '<li', '<a' ],
		[
			'<ul aria-label="Archive navigation" itemtype="https://schema.org/SiteNavigationElement" itemscope',
			'<li itemprop="name"',
			'<a itemprop="url"'
		],
		$block_content
	);
}

/**
 * Adds role="alert" to .alert elements in core/group blocks.
 */
add_filter( 'render_block', function ( $block_content, $block ) {
	if ( empty( $block_content ) || $block['blockName'] !== 'core/group' ) {
		return $block_content;
	}

	if ( strpos( $block_content, 'alert' ) !== false && ! preg_match( '/role=["\']alert["\']/i', $block_content ) ) {
		$block_content = preg_replace(
			'/(<[^>]*class=["\'][^"\']*alert[^"\']*["\'][^>]*)(>)/i',
			'$1 role="alert" itemtype="https://schema.org/CommunicateAction" itemscope $2',
			$block_content
		);
	}

	return $block_content;
}, 10, 2 );

/**
 * Adds role="toolbar" and an aria-label to .toolbar elements in core/group blocks.
 */
add_filter( 'render_block', function ( $block_content, $block ) {
	if ( empty( $block_content ) || ( $block['blockName'] ?? '' ) !== 'core/group' ) {
		return $block_content;
	}

	if ( strpos( $block_content, 'toolbar' ) !== false ) {
		$block_content = preg_replace(
			'/(<[^>]*class=["\'][^"\']*toolbar[^"\']*["\'][^>]*)(>)/i',
			'$1 role="toolbar" aria-label="Toolbar with button groups"$2',
			$block_content
		);
	}

	return $block_content;
}, 10, 2 );

/**
 * Adds role="group" and an aria-label to .button-group elements in core/buttons blocks.
 */
add_filter( 'render_block', function ( $block_content, $block ) {
	if ( empty( $block_content ) || ( $block['blockName'] ?? '' ) !== 'core/buttons' ) {
		return $block_content;
	}

	if ( strpos( $block_content, 'button-group' ) !== false ) {
		$block_content = preg_replace(
			'/(<[^>]*class=["\'][^"\']*button-group[^"\']*["\'][^>]*)(>)/i',
			'$1 role="group" aria-label="Button Group"$2',
			$block_content
		);
	}

	return $block_content;
}, 10, 2 );

/**
 * Adds role="button" to anchor elements inside core/button blocks.
 */
add_filter( 'render_block', function ( $block_content, $block ) {
	if ( empty( $block_content ) || ( $block['blockName'] ?? '' ) !== 'core/button' ) {
		return $block_content;
	}

	if ( strpos( $block_content, '<a ' ) !== false && strpos( $block_content, 'role="button"' ) === false ) {
		$block_content = preg_replace(
			'/(<a\s+[^>]*class=["\'][^"\']*wp-block-button__link[^"\']*["\'][^>]*)(>)/i',
			'$1 role="button"$2',
			$block_content
		);
	}

	return $block_content;
}, 10, 2 );

/**
 * Adds role="button" to .button elements, excluding .wp-block-button.
 */
add_filter( 'render_block', function ( $block_content, $block ) {
	if ( empty( $block_content ) ) {
		return $block_content;
	}

	if ( strpos( $block_content, 'class="' ) !== false && strpos( $block_content, 'button' ) !== false ) {
		$block_content = preg_replace_callback(
			'/<([a-z]+)([^>]*class=["\'][^"\']*\bbutton\b[^"\']*["\'][^>]*)>/i',
			function ( $matches ) {
				if ( strpos( $matches[2], 'wp-block-button' ) === false && strpos( $matches[2], 'role=' ) === false ) {
					return "<{$matches[1]}{$matches[2]} role=\"button\">";
				}
				return $matches[0];
			},
			$block_content
		);
	}

	return $block_content;
}, 10, 2 );

/**
 * Adds aria-disabled="true" to disabled core/button elements.
 */
add_filter( 'render_block', function ( $block_content, $block ) {
	if ( empty( $block_content ) || $block['blockName'] !== 'core/button' ) {
		return $block_content;
	}

	if ( strpos( $block_content, 'class="' ) !== false && strpos( $block_content, 'disabled' ) !== false ) {
		$block_content = preg_replace(
			'/(<[^>]*class=["\'][^"\']*\bdisabled\b[^"\']*["\'][^>]*)>/i',
			'$1 aria-disabled="true" tabindex="-1">',
			$block_content
		);
	}

	if ( strpos( $block_content, '<button' ) !== false && strpos( $block_content, 'disabled' ) !== false ) {
		$block_content = preg_replace(
			'/(<button[^>]*\bdisabled\b[^>]*)>/i',
			'$1 aria-disabled="true" tabindex="-1">',
			$block_content
		);
	}

	return $block_content;
}, 10, 2 );

/**
 * Adds aria-label="breadcrumb" to core/group blocks with class breadcrumbs.
 */
add_filter( 'render_block', function ( $block_content, $block ) {
	if ( empty( $block_content ) || ( $block['blockName'] ?? '' ) !== 'core/group' ) {
		return $block_content;
	}

	if ( strpos( $block_content, 'breadcrumbs' ) !== false && ! preg_match( '/aria-label=["\']breadcrumb["\']/i', $block_content ) ) {
		$block_content = preg_replace(
			'/(<[^>]*class=["\'][^"\']*\bbreadcrumbs\b[^"\']*["\'][^>]*)(>)/i',
			'$1 aria-label="breadcrumb"$2',
			$block_content
		);
	}

	return $block_content;
}, 10, 2 );

/**
 * Scans core/group blocks for specific classes and replaces <p class="close"> elements inside with <button> elements.
 */
add_filter( 'render_block', function ( $block_content, $block ) {
	if ( empty( $block_content ) || ( $block['blockName'] ?? '' ) !== 'core/group' ) {
		return $block_content;
	}

	$contexts = [ 'alert', 'modal', 'offcanvas', 'toast' ];

	foreach ( $contexts as $context ) {
		if ( strpos( $block_content, $context ) !== false ) {
			$block_content = preg_replace_callback(
				'/<([a-z1-6]+)([^>]*)class=["\']([^"\']*\bclose\b[^"\']*)["\']([^>]*)>(.*?)<\/\1>/i',
				function ( $matches ) use ( $context ) {
					$classes = esc_attr( $matches[3] );
					return sprintf(
						'<button class="%s" type="button" data-bs-dismiss="%s" aria-label="Close"></button>',
						$classes,
						esc_attr( $context )
					);
				},
				$block_content
			);
			break;
		}
	}

	return $block_content;
}, 10, 2 );

/**
 * Filter: Adds schema.org markup to core/site-logo blocks.
 */
add_filter( 'render_block_core/site-logo', 'strap_site_logo_block_filter', 10, 2 );
function strap_site_logo_block_filter( string $block_content, array $block ): string {
	if ( empty( $block_content ) ) {
		return $block_content;
	}

	$block_content = strap_replace_block_content(
		$block_content,
		'<img',
		'<img itemprop="logo"'
	);

	if ( strpos( $block_content, '<a ' ) !== false ) {
		$block_content = strap_replace_block_content(
			$block_content,
			'<a ',
			'<a itemscope itemtype="https://schema.org/ImageObject" '
		);
	} else {
		$block_content = strap_replace_block_content(
			$block_content,
			'<img',
			'<img itemscope itemtype="https://schema.org/ImageObject"'
		);
	}

	return $block_content;
}

/**
 * Filter: Adds aria-label and role to core/social-links blocks.
 */
add_filter( 'render_block_core/social-links', 'strap_social_links_block_filter', 10, 2 );
function strap_social_links_block_filter( string $block_content, array $block ): string {
	if ( empty( $block_content ) ) {
		return $block_content;
	}

	return strap_replace_block_content(
		$block_content,
		'<ul',
		'<ul role="list" aria-label="Social profiles"'
	);
}

/**
 * Filter: Adds schema.org markup to core/quote and core/pullquote blocks.
 */
function strap_quote_block_filter( string $block_content, array $block ): string {
	if ( empty( $block_content ) ) {
		return $block_content;
	}

	return strap_replace_block_content(
		$block_content,
		'<blockquote',
		'<blockquote itemscope itemtype="https://schema.org/Quotation"'
	);
}
add_filter( 'render_block_core/quote', 'strap_quote_block_filter', 10, 2 );
add_filter( 'render_block_core/pullquote', 'strap_quote_block_filter', 10, 2 );

/**
 * Filter: Adds schema.org markup to core/gallery blocks.
 */
add_filter( 'render_block_core/gallery', 'strap_gallery_block_filter', 10, 2 );
function strap_gallery_block_filter( string $block_content, array $block ): string {
	if ( empty( $block_content ) ) {
		return $block_content;
	}

	return strap_replace_block_content(
		$block_content,
		'<figure',
		'<figure itemscope itemtype="https://schema.org/ImageGallery"'
	);
}

/**
 * Filter: Adds aria-label and role to core/post-terms blocks.
 */
add_filter( 'render_block_core/post-terms', 'strap_post_terms_block_filter', 10, 2 );
function strap_post_terms_block_filter( string $block_content, array $block ): string {
	if ( empty( $block_content ) ) {
		return $block_content;
	}

	$label = 'Post taxonomy';
	if ( ! empty( $block['attrs']['term'] ) ) {
		$label = 'Post ' . esc_attr( $block['attrs']['term'] );
	}

	$block_content = strap_replace_block_content(
		$block_content,
		'class="',
		'role="list" aria-label="' . $label . '" class="'
	);

	return $block_content;
}

/**
 * Filter: Adds schema.org markup to core/video blocks.
 */
add_filter( 'render_block_core/video', 'strap_video_block_filter', 10, 2 );
function strap_video_block_filter( string $block_content, array $block ): string {
	if ( empty( $block_content ) ) {
		return $block_content;
	}

	return strap_replace_block_content(
		$block_content,
		'<figure',
		'<figure itemscope itemtype="https://schema.org/VideoObject"'
	);
}

/**
 * Filter: Adds schema.org markup to core/audio blocks.
 */
add_filter( 'render_block_core/audio', 'strap_audio_block_filter', 10, 2 );
function strap_audio_block_filter( string $block_content, array $block ): string {
	if ( empty( $block_content ) ) {
		return $block_content;
	}

	return strap_replace_block_content(
		$block_content,
		'<figure',
		'<figure itemscope itemtype="https://schema.org/AudioObject"'
	);
}
/* ==========================================================================
   BuddyPress Semantic HTML / ARIA Filters
   ========================================================================== */
/**
 * Filter: Adds aria-label and semantic roles to BuddyPress patterns.
 */
add_filter( 'render_block_core/group', 'strap_buddypress_semantic_block_filter', 10, 2 );
function strap_buddypress_semantic_block_filter( string $block_content, array $block ): string {
	$class_name = strap_get_class_name( $block );

	if ( str_contains( $class_name, 'buddypress-activity-pattern' ) ) {
		return strap_replace_block_content(
			$block_content,
			'class',
			'role="feed" aria-label="Activity Feed" class'
		);
	}

	if ( str_contains( $class_name, 'buddypress-members-pattern' ) ) {
		return strap_replace_block_content(
			$block_content,
			'class',
			'aria-label="Members Directory" class'
		);
	}

	if ( str_contains( $class_name, 'buddypress-groups-pattern' ) ) {
		return strap_replace_block_content(
			$block_content,
			'class',
			'aria-label="Groups Directory" class'
		);
	}

	if ( str_contains( $class_name, 'buddypress-blogs-pattern' ) ) {
		return strap_replace_block_content(
			$block_content,
			'class',
			'aria-label="Sites Directory" class'
		);
	}

	return $block_content;
}
